import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import AppWrapper from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <AppWrapper>
            <Navbar />
            {children}
            <Toaster position="top-right" reverseOrder={false} />
          </AppWrapper>
        </ChakraProvider>
      </body>
    </html>
  );
}
